title: AFK Super Cool Site
description: This is a great website!

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
